---

- name: Install dnsmasq package
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: False
  tags: install
  with_items: [ 'dnsmasq', 'resolvconf' ]

- name: Get list of local search domains
  shell: grep search /etc/resolv.conf | cut -d' ' -f2- | tr ' ' '\n'
  register: dnsmasq_register_search
  changed_when: False

- name: Get dnsmasq version
  shell: dnsmasq --version | head -n 1 | awk '{print $3}'
  register: dnsmasq_version
  changed_when: False

- name: Create main dnsmasq configuration
  template:
    src: 'etc/dnsmasq.d/00_main.conf.j2'
    dest: '/etc/dnsmasq.d/00_main.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Test and restart dnsmasq' ]

- name: Create interface dnsmasq configuration
  template:
    src: 'etc/dnsmasq.d/interface.conf.j2'
    dest: '/etc/dnsmasq.d/interface_{{ item.interface }}.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: dnsmasq_interfaces
  when: item.interface is defined and item.interface
  notify: [ 'Test and restart dnsmasq' ]
