---

# Configuration for Debian Netboot Installer
dnsmasq_netboot_debian_root: '{{ dnsmasq_tftp_root }}'
dnsmasq_netboot_debian_source: 'http://cdn.debian.net/debian/dists/wheezy/main/installer-amd64/current/images/netboot/netboot.tar.gz'
dnsmasq_netboot_debian_archive: '/usr/local/src/dnsmasq_netboot/debian/netboot.tar.gz'
dnsmasq_netboot_debian_creates: '{{ dnsmasq_netboot_debian_root }}/version.info'

